version: '3'
services:
  gate_service: 
    build: .
    command: rails s -b 0.0.0.0 
    volumes:
      - .:/usr/src
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres:/var/lib/postgresql/data
      # - .:/src
volumes:
  postgres:
