# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  host: gate_db
  user: user
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> 
  timeout: 5000

development:
  <<: *default 
  database: gate_development

test:
  <<: *default
  database: gate_test

production:
  <<: *default
  database: gate_production